"""add territory to faction_state_snapshots

Revision ID: 2b1c7dbb9312
Revises: 157d15fc6345
Create Date: 2026-09-12 15:37:02.243839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b1c7dbb9312'
down_revision: Union[str, Sequence[str], None] = '157d15fc6345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default added by hand: autogenerate's bare `nullable=False`
    # would fail on any existing rows (table happens to be empty right now,
    # but this column shouldn't depend on that happening to stay true).
    op.add_column(
        'faction_state_snapshots',
        sa.Column(
            'territory',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faction_state_snapshots', 'territory')
    # ### end Alembic commands ###
