"""add users table and scenario owner

Revision ID: 493bb1b6f7d8
Revises: 1022ae49fdae
Create Date: 2026-09-13 19:51:29.269046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493bb1b6f7d8'
down_revision: Union[str, Sequence[str], None] = '1022ae49fdae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('picture_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.add_column('scenarios', sa.Column('owner_user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_scenarios_owner_user_id'), 'scenarios', ['owner_user_id'], unique=False)
    # Named explicitly — autogenerate left this unnamed (None), which
    # renders a downgrade() that fails outright (no naming convention is
    # configured in db/migrations/env.py). Same class of gap CLAUDE.md's
    # Persistence notes already caught once before (the games/game_factions
    # mutual FK); fixed the same way, by naming it before it ships.
    op.create_foreign_key(
        'fk_scenarios_owner_user_id_users', 'scenarios', 'users',
        ['owner_user_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_scenarios_owner_user_id_users', 'scenarios', type_='foreignkey')
    op.drop_index(op.f('ix_scenarios_owner_user_id'), table_name='scenarios')
    op.drop_column('scenarios', 'owner_user_id')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
